spring:
  datasource:
    url: jdbc:oracle:thin:@10.1.50.129:1521:orcl
    username: system
    password: oracledba
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    auto-commit: false